format = """
$directory$git_branch$git_status$character
"""

[directory]
style = "bold #d8a657"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bold #a9b665"
symbol = " "

[git_status]
style = "bold #ea6962"

[character]
success_symbol = "[❯](bold #b8bb26)"
error_symbol = "[❯](bold #ea6962)"